astronaut_full_name = input("Enter astronaut's full name: ")
print(f"Originnal name: {astronaut_full_name}")
astronaut_full_name = astronaut_full_name.upper()
astronaut_full_name = astronaut_full_name.replace(" ", "_")
print(f"Processed name tage: {astronaut_full_name}")